### ISSUE TITLE
[Breaking Change] Support CLI flags for different reporters

### ISSUE THREAD

**Issue by willemneal** [jtenner/as-pect#108]
Since `--reporter=SummaryTestReporter` is so common and a lot to type it would be better to provide an alias.  Also as a side aspect to this issue, reporters should be renamed; the suffix `TestReporter` is redundant.  Like `BufferOverflowError` doesn't need the `Error`.

**Comment by jtenner** [comment]
Alright. It might be a good idea to make the summary reporter the default reporter

**Comment by jtenner** [comment]
Can we keep this off for v2.0.0?

**Comment by jtenner** [comment]
Yeah for version `2.0.0` we should break compatibility and use special flags.

- [ ] add `CombinationReporter` that takes a set of reporters, and reports to all of them
- [ ] Remove `--reporter` flag, in favor of using `CombinationReporter`  with the following flags:
  - [ ] add `--summary=urlEncodedOptions` for `SummaryReporter` (renamed)
  - [ ] add `--csv=urlEncodedOptions` for `CSVReporter` (renamed)
  - [ ] add `--json=urlEncodedOptions` for `JSONReporter` (renamed)
  - [ ] add `--verbose=urlEncodedOptions` for `VerboseReporter` (renamed from DefaultTestReporter)
- [ ] default to `SummaryReporter` with default logging turned on (add option to turn logging off instead of other way around) unless any of these flags are present
