### ISSUE TITLE
Type declarations for as-pect

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#166]
I have type declarations in https://github.com/infamous/glas/blob/master/assembly/__tests__/as-pect.d.ts. Just wondering, is that still the way to do it? Or do they get installed from NPM now?

**Comment by jtenner** [comment]
The `@as-pect/assembly` package contains the types you need. I think I need to update the CLI process to update the types more properly. Actually.

@willemneal How should we handle the types? Sometimes they need to get updated and they currently get added to the project manually.

**Comment by willemneal** [comment]
Yeah this is a problem with upstream assemlyscript too.  We've become accustom to inheriting the tsconfig from assemblyscript (which I'm annoyed must be relative as I don't know of a way to rely on a package in a tsconfig), meaning that it restricts the types to a folder in its repo, instead of say relying on a namespace like ts does with @types.

This is a tooling issue that we should aim to fix so that as more people take advantage of global types it isn't a headache.

**Comment by jtenner** [comment]
We could do it like I recommend.

Add a <reference> tag to the top of a d.ts file pointing at the assembly types in the generated d.ts file.
