### ISSUE TITLE
Switch to passing null

### ISSUE THREAD

**Issue by jtenner** [jtenner/as-pect#202]
https://github.com/jtenner/as-pect/blob/master/packages/assembly/assembly/internal/comparison/toIncludeComparison.ts#L26

The toIncludeEqualsComparison function should also be be refactored to:

```ts
Expected.report<T>(null, 1);
```

**Comment by DuncanUszkay1** [comment]
I'm not convinced this line makes sense- here's an example:

I write this test:
```typescript
expect<Array<i32> | null>(null).toInclude(2);
```
That returns this result:
```typescript
❌ assembly/__tests__/example.spec.ts Pass: 6 / 7 Todo: 0 Time: 6.163ms
  Failed: example
    ❌ should fail toIncludeEquals if expected is null -
      [Expected]: null
      [Actual]  : null
```
But I don't think that output is actually correct- I'm not expecting the value null. There is no value I could have put into the expected field that would have made this test pass.

If we just delete that line you're referencing we get this output instead which I think makes more sense:
```typescript
❌ assembly/__tests__/example.spec.ts Pass: 6 / 7 Todo: 0 Time: 8.577ms
  Failed: example
    ❌ should fail toIncludeEquals if expected is null -
      [Actual]  : null
```
Since `actual` being null is what caused the test to fail

**Comment by jtenner** [comment]
The test failed because actual value is null. There is an assertion that makes sure the actual value is null. Output should be ACTUAL value. Not EXPECTED value. I'll get around to that later.
