### ISSUE TITLE
as-pect with nightly version of assemblyscript

### ISSUE THREAD

**Issue by alexvictoor** [jtenner/as-pect#292]
Hello
First thanks a lot for as-pect, I love it :)
I have tried to run my tests with latest nightly build of assemblyscript. I get a weird error: "TypeError: Cannot read property 'sources' of undefined"

I am using as-pect 3.1.6. 
Is there an additional config needed in order to use as-pect with an assemblyscript nightly build?

**Comment by jtenner** [comment]
Yes. `as-pect` only supports the latest stable version of AssemblyScript. I am waiting for @dcode to slice version 0.10 to support the new loader semantics.

Please use version `0.9.4`. If you need to use the new version, it's possible to slice a `@beta` build and release it, but that will take some time to get around to.

Feel free to keep this issue open until this issue is resolved.

**Comment by alexvictoor** [comment]
Thanks a lot for your answer!
I guess the as-pect getting started doc should be updated since it leads to
install assemblyscript nightly.

**Comment by jtenner** [comment]
Looks like assemblyscript 0.10 was sliced today. I will be trying to get this working by tonight so you can start working with as-pect tomorrow.

**Comment by jtenner** [comment]
As it turns out, the problem you were experiencing was a parser refactor that decoupled the `Parser` from the `Program` object internally in AssemblyScript.

I will be releasing `as-pect` version 4.0.0 soon.
