### ISSUE TITLE
possible to specify location of .wat and .map files?

### ISSUE THREAD

**Issue by bcolloran** [jtenner/as-pect#331]
I've looked over the docs a couple times, apologies if I've missed it somewhere, but is it possible to specify the location of the .wat and .map files created by as-pect? If this is not possible today, it would useful config to create a config option that would allow these files to be written somewhere other than the directory containing the test. Thanks!

**Comment by jtenner** [comment]
I understand that this is an inconvenience. I'm not entirely sure the direction I should take the software at the moment, and because I'm trying to work out an entire CLI rewrite, it may be possible to address this in the future. In the meantime, I believe writing the wat/map/wasm files directly next to to the test file is specifically a feature of the current branch.

**Comment by jtenner** [comment]
Yes. This is a feature, designed this way as the opinionated way to generate the wasm/wat/map files. I'm going to close this as `wontfix`
