### ISSUE TITLE
rtrace branch is a few seconds slower than runtime branch

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#90]
I had to switch back to the `runtime` branch for now, as the tests begin almost immediately. On the `rtrace` branch, it takes several seconds before any tests start.

By the way, what is "RTrace"?

**Comment by jtenner** [comment]
If there is a performance startup problem it's because there is a Javascript issue. I can't put my finger on it and @willemneal pointed this out to me.

Rtrace is the reference counting reporting that should help you find memory leaks in your software.

As for the slowness? Value program correctness first. There were lots of bug fixes that came with that branch.

It's up to you.

**Comment by jtenner** [comment]
I have a feeling we can increase startup time to make the software feel less sluggish by using the require function *after* arguments have been parsed.

**Comment by jtenner** [comment]
I have addressed this problem, and even the `--help` screen now loads and starts up faster.

I cannot make the testing algorithm much faster because `as-pect` desires test algorithm correctness over speed. However, there shouldn't be a large amount of start-up time when the fix is simply to switch to `require()` function calls.

Please see the `configuration-warnings` branch and try it out for yourself.

Please note that your performance configuration might need to change because the default `maxRunTime` option was `Infinity` and will flood your console with configuration warnings.

**Comment by trusktr** [comment]
> Value program correctness first. There were lots of bug fixes that came with that branch.

Cool. So far so good, tests passing on runtime branch.
