### ISSUE TITLE
Failed expectation in test with no expectations

### ISSUE THREAD

**Issue by trusktr** [jtenner/as-pect#92]
I've got a test like this:

```ts
	describe('.traverse/.traverseVisible/.traverseAncestors', () => {
		test('they traverse up and down the tree', () => {
			a.name = 'parent'
			b.name = 'child'
			c.name = 'childchild 1'
			c.visible = false
			d.name = 'childchild 2'

			b.add(c)
			b.add(d)
			a.add(b)

			a.traverse(function(obj) {
				names.push(obj.name)
			})

		})
	})
```

It fails on `runtime`, `rtrace` and `configuration-warnings`, but there's not really any output on rtrace or config branches.

The only somewhat interesting output is on the runtime branch:

```
❌ src/as/glas/core/Object3D.spec.ts Pass: 1 / 2 Todo: 0 Time: 3.515ms
  Object3D.traverse/.traverseVisible/.traverseAncestors
    ❌ they traverse up and down the tree - 
      [Expected]: null
      [Actual]  : null
```

The odd part is that if you delete the `traverse` block, so:

```ts
	describe('.traverse/.traverseVisible/.traverseAncestors', () => {
		test('they traverse up and down the tree', () => {
			a.name = 'parent'
			b.name = 'child'
			c.name = 'childchild 1'
			c.visible = false
			d.name = 'childchild 2'

			b.add(c)
			b.add(d)
			a.add(b)
		})
	})
```

then the test passes.

**Comment by trusktr** [comment]
reproduction:

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout as-pect-issue-92
npm i
npm test
```

**Comment by trusktr** [comment]
The file is `src/as/glas/core/Object3D.spec.ts`

**Comment by jtenner** [comment]
Listen. Not every error is aspects fault. Sometimes, you have a bad function that emits an unreachable without a reason. There's no message here, and the actual/expected values are red herrings.

I can fix the false output, maybe, but it's gonna take time to iron these things out.

Change your compiler flags and take a look at the test function to see where the problem is by adding `--textFile output.wat`.

Go take a look at the wat file it generates and try to trace where the unreachable instruction is.

**Comment by willemneal** [comment]
I tried this out and it seems this is a runtime issue; I got the following error:
```
[Describe]: Object3D.traverse/.traverseVisible/.traverseAncestors

    [Fail]: ✖ they traverse up and down the tree

   [Actual]: null
               at node_modules/as-pect/assembly/internal/report/reportActual/__sendActual (wasm-function[106]:115)

 [Expected]: null
               at node_modules/as-pect/assembly/internal/report/reportExpected/__sendExpected (wasm-function[107]:150)

    [Stack]: Error: not a string: 0
               at ~lib/rt/tlsf/insertBlock (wasm-function[25]:342)
               at ~lib/rt/tlsf/reallocateBlock (wasm-function[79]:231)
               at ~lib/rt/tlsf/__realloc (wasm-function[80]:61)
               at ~lib/array/ensureSize (wasm-function[82]:66)
               at ~lib/array/Array<~lib/string/String>#push (wasm-function[97]:28)
               at start:src/as/glas/core/Object3D.spec~anonymous|0~anonymous|1~anonymous|0~anonymous|0 (wasm-function[98]:13)
               at src/as/glas/core/Object3D/Object3D#traverse (wasm-function[99]:11)

  [Result]: ✖ FAIL
   [Tests]: 0 pass, 1 fail, 1 total
    [Todo]: 0 tests
    [Time]: 2.4ms
```

  When I changed the config to `"--runtime", ["stub"]`, it passed.  In this particular case I found that the issue was with initializing the array `names` with an array literal.  Changing the line at the top of the file to

```ts
const names: string[] = new Array<string>()
```

made it pass the test.  I've been burned by empty array literals in the past and I would avoid them.  Perhaps you could make as issue with AS letting them know about this.

**Comment by jtenner** [comment]
Yeah, this is a language problem, sadly.

**Comment by trusktr** [comment]
Ah, I see. Based on the errors, I would've never guessed!

> try to trace where the unreachable instruction

When I do, it will be my first time reading Wasm code (well, I've looked at what it looks like at a high level, but I haven't gone and understood every instruction yet).

Anywho, sorry about all the reports!

From an end user perspective (coming from JS with no experience in actual Wasm code), it's just that I am getting stuck without any meaningful clues (regardless if it is as-pect's, assemblyscript's, or my fault), but I'm sure these things will improve over time and eventually reach a higher level of meaningful error messaging.

I'm definitely not pointing any fingers. However, if I run into an error that doesn't tell me anything, I feel to report it somewhere, so I have to choose between as-pect and assemblyscript repos, and sometimes I might be wrong (which is understandable considering the nature of the error messages).

F.e., I decided to report https://github.com/AssemblyScript/assemblyscript/issues/649, which was in the wrong place. Then I opened this very issue, and this one's in the wrong place.

So, the situation is a little tricky from an end-user perspective, but I know the polish is being put on as we speak. :)

**Comment by jtenner** [comment]
You are trailblazing on a brand new compiler and dialect of typescript. Weird, difficult and strange problems are going to hit you. I agree with @willemneal on his advice and I can try to help you when I'm not fixing a ton of bugs and writing a ton of documentation :).

I just want to impose upon myself a stricter ruleset when asking for help.

It would be a great start to learn what the wat file output *means* and how to trace function calls using it. Take some time and read the web assembly specification and learn something new!

**Comment by trusktr** [comment]
Indeed I'll get there. It's going to take some time.

@willemneal How did you enable the detailed stack output? And how did you realize that was the problem?

**Comment by willemneal** [comment]
You might need to update your local version of `as-pect` as I didn't change anything in your setup.  I just used a `log<string>(obj.name)` before and after the push and it only printed the first time, so then I new that it was with how the array was allocated.  And from my experience with being burned by empty array literals.  The other problems that they had in the past was that since the compiler see it as a literal it lifted it up to the global scope and multiple calls to the a function that declare a literal would still point to that global array.  Using the constructor is pretty much always the best way to go.

I can tell from your posts that you are attached to the syntax you've become accustom to.  However, I think it's a fair compromise if you get type safety and speed.  Also there are others in the works.  I'm currently working on implementing iterators so that you can use `for (let x of arr)` among other useful features that are currently unavailable.  I say this not to stop you from making future issues about lack of features as it is good for new people to find, but just to expect to write less flexible syntax.

**Comment by jtenner** [comment]
There were some issues with stack trace values. Also the default reporter has a lot of output.

**Comment by jtenner** [comment]
I don't know if this is still an issue. Can @trusktr confirm?

**Comment by jtenner** [comment]
Also the stack traces for actual and expected values have much better output now.

**Comment by jtenner** [comment]
@trusktr @willemneal this particular issue is the result of a `assert(false)` that calls out to the JavaScript `env.abort()` web assembly import.

```
Error: not a string: 0
```

Instead, it will now say `"No assertion message provided."`
